# Generated by Django 4.0.6 on 2022-08-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0002_human'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='human',
            old_name='name',
            new_name='name1',
        ),
    ]
